#!/bin/sh

# $Id: set-version 4769 2004-12-06 22:13:42Z davea $

# Change boinc version number in configure.ac and generate files.

# syntax: set-version 7.17

die()
{
    echo "$@" >&2
    exit 1
}

cmd()
{
    "$@" || die "couldn't $*"
}

if [ "$1" ]; then
    echo "Setting QCN version to $1."

    cmd mv configure.ac configure.ac.old
    cmd sed "s/^AC_INIT.*/AC_INIT(QCN, $1)/" configure.ac.old > configure.ac
else
    echo "Updating files for QCN version (assuming you manually changed configure.ac)"
fi

