update user set global_prefs=concat('<global_preferences>
<mod_time>',unix_timestamp(),'</mod_time>
<leave_apps_in_memory>0</leave_apps_in_memory>
<suspend_while_on_batteries>0</suspend_while_on_batteries>
<idle_time_to_run>3</idle_time_to_run>
<suspend_if_no_recent_input>0</suspend_if_no_recent_input>
<cpu_scheduling_period_minutes>60</cpu_scheduling_period_minutes>
<work_buf_min_days>0</work_buf_min_days>
<work_buf_additional_days>0.25</work_buf_additional_days>
<max_cpus>1</max_cpus>
<cpu_usage_limit>100</cpu_usage_limit>
<disk_interval>60</disk_interval>
<disk_max_used_gb>100</disk_max_used_gb>
<disk_max_used_pct>50</disk_max_used_pct>
<disk_min_free_gb>0.001</disk_min_free_gb>
<vm_max_used_pct>75</vm_max_used_pct>
<ram_max_used_busy_pct>50</ram_max_used_busy_pct>
<ram_max_used_idle_pct>90</ram_max_used_idle_pct>
<max_bytes_sec_down>0</max_bytes_sec_down>
<max_bytes_sec_up>0</max_bytes_sec_up>
</global_preferences>');
