#############################################################################
# Makefile for building: QCNLive.app/Contents/MacOS/QCNLive
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Sep 15 12:50:11 2011
# Project:  QCNLive.pro
# Template: app
# Command: /Developer/Qt/bin/qmake -spec /Developer/Qt474/mkspecs/macx-xcode -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro
#############################################################################

QMAKE    = /Developer/Qt/bin/qmake
QCNLive.xcodeproj/project.pbxproj: QCNLive.pro  /Developer/Qt474/mkspecs/macx-xcode/qmake.conf /Developer/Qt474/mkspecs/common/unix.conf \
		/Developer/Qt474/mkspecs/common/mac.conf \
		/Developer/Qt474/mkspecs/common/mac-g++.conf \
		/Developer/Qt474/mkspecs/qconfig.pri \
		/Developer/Qt474/mkspecs/modules/qt_webkit_version.pri \
		/Developer/Qt474/mkspecs/features/qt_functions.prf \
		/Developer/Qt474/mkspecs/features/qt_config.prf \
		/Developer/Qt474/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt474/mkspecs/features/default_pre.prf \
		/Developer/Qt474/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt474/mkspecs/features/mac/dwarf2.prf \
		/Developer/Qt474/mkspecs/features/debug.prf \
		/Developer/Qt474/mkspecs/features/default_post.prf \
		/Developer/Qt474/mkspecs/features/mac/default_post.prf \
		/Developer/Qt474/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt474/mkspecs/features/mac/x86_64.prf \
		/Developer/Qt474/mkspecs/features/mac/x86.prf \
		/Developer/Qt474/mkspecs/features/warn_on.prf \
		/Developer/Qt474/mkspecs/features/qt.prf \
		/Developer/Qt474/mkspecs/features/unix/opengl.prf \
		/Developer/Qt474/mkspecs/features/unix/thread.prf \
		/Developer/Qt474/mkspecs/features/moc.prf \
		/Developer/Qt474/mkspecs/features/mac/rez.prf \
		/Developer/Qt474/mkspecs/features/mac/sdk.prf \
		/Developer/Qt474/mkspecs/features/resources.prf \
		/Developer/Qt474/mkspecs/features/uic.prf \
		/Developer/Qt474/mkspecs/features/yacc.prf \
		/Developer/Qt474/mkspecs/features/lex.prf \
		/Developer/Qt474/mkspecs/features/include_source_dir.prf \
		/Developer/Qt/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Developer/Qt/lib/QtGui.framework/QtGui.prl \
		/Developer/Qt/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /Developer/Qt474/mkspecs/macx-xcode -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro
/Developer/Qt474/mkspecs/common/unix.conf:
/Developer/Qt474/mkspecs/common/mac.conf:
/Developer/Qt474/mkspecs/common/mac-g++.conf:
/Developer/Qt474/mkspecs/qconfig.pri:
/Developer/Qt474/mkspecs/modules/qt_webkit_version.pri:
/Developer/Qt474/mkspecs/features/qt_functions.prf:
/Developer/Qt474/mkspecs/features/qt_config.prf:
/Developer/Qt474/mkspecs/features/exclusive_builds.prf:
/Developer/Qt474/mkspecs/features/default_pre.prf:
/Developer/Qt474/mkspecs/features/mac/default_pre.prf:
/Developer/Qt474/mkspecs/features/mac/dwarf2.prf:
/Developer/Qt474/mkspecs/features/debug.prf:
/Developer/Qt474/mkspecs/features/default_post.prf:
/Developer/Qt474/mkspecs/features/mac/default_post.prf:
/Developer/Qt474/mkspecs/features/mac/objective_c.prf:
/Developer/Qt474/mkspecs/features/mac/x86_64.prf:
/Developer/Qt474/mkspecs/features/mac/x86.prf:
/Developer/Qt474/mkspecs/features/warn_on.prf:
/Developer/Qt474/mkspecs/features/qt.prf:
/Developer/Qt474/mkspecs/features/unix/opengl.prf:
/Developer/Qt474/mkspecs/features/unix/thread.prf:
/Developer/Qt474/mkspecs/features/moc.prf:
/Developer/Qt474/mkspecs/features/mac/rez.prf:
/Developer/Qt474/mkspecs/features/mac/sdk.prf:
/Developer/Qt474/mkspecs/features/resources.prf:
/Developer/Qt474/mkspecs/features/uic.prf:
/Developer/Qt474/mkspecs/features/yacc.prf:
/Developer/Qt474/mkspecs/features/lex.prf:
/Developer/Qt474/mkspecs/features/include_source_dir.prf:
/Developer/Qt/lib/QtOpenGL.framework/QtOpenGL.prl:
/Developer/Qt/lib/QtGui.framework/QtGui.prl:
/Developer/Qt/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /Developer/Qt474/mkspecs/macx-xcode -o QCNLive.xcodeproj/project.pbxproj QCNLive.pro

